Repository hmcts/finrem-document-generator-client, pull requests merged in 2020-10, with the labels that each got.

#86 fix dependency check error
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-86

#87 upgrade terraform to 13.4
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-87

#88 bump versions
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-88

#89 dependency check suppression
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-89

#90 fix failed functional test
  src/functionalTests/resources/json/bulkprinting.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-90
