Repository hmcts/finrem-document-generator-client, pull requests merged in 2020-06, with the labels that each got.

#74 Bump tomcat verison
  build.gradle
Labels: ns:financial-remedy, rel:finrem-dgcs-pr-74

#75 Update security.sh
  audit.json
  security.sh
Labels: ns:financial-remedy, rel:finrem-dgcs-pr-75

#76 add false positives
  audit.json
Labels: ns:financial-remedy, rel:finrem-dgcs-pr-76

#77 enable mutation tests
  Jenkinsfile_nightly
  README.md
  build.gradle
Labels: ns:financial-remedy, rel:finrem-dgcs-pr-77
