Repository hmcts/finrem-document-generator-client, pull requests merged in 2022-08, with the labels that each got.

#136 DFR-1086 Update Readme
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-136

#137 Add backstage configuration file
  catalog-info.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-137

#138 DFR-1298 Fix FT
  src/functionalTests/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-138
