Repository hmcts/finrem-document-generator-client, pull requests merged in 2022-05, with the labels that each got.

#120 Autoscaling finrem-dgcs Update Chart.yaml
  charts/finrem-dgcs/Chart.yaml
  charts/finrem-dgcs/values.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-120

#123 Bumping tomcat
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-123

#124 Bumping springframework
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-124
