Repository hmcts/finrem-document-generator-client, pull requests merged in 2022-07, with the labels that each got.

#132 DFR-1172: Suppress log4j vulnerability
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-132

#134 Bumping tika-core to 1.28.4
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-134

#135 DFR-1211: java chart version
  charts/finrem-dgcs/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-135
