Repository hmcts/finrem-document-generator-client, pull requests merged in 2022-06, with the labels that each got.

#126 Bumping tika-core to 1.28.3
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-126

#127 DTSSE-1602 - update chart repo reference for flux v2 migration
  charts/finrem-dgcs/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-127

#128 DFR-1162: Enable Renovate
  .github/renovate.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-dgcs-pr-128
